"""add version_id

Revision ID: 1756389380dc
Revises: d1df98cc3ec1
Create Date: 2024-08-17 21:47:35.726432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1756389380dc'
down_revision: Union[str, None] = 'd1df98cc3ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seckill', sa.Column('version_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seckill', 'version_id')
    # ### end Alembic commands ###
