"""add model

Revision ID: 3467fe4efc1c
Revises: 093a3b670ff0
Create Date: 2024-08-15 21:42:36.962039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3467fe4efc1c'
down_revision: Union[str, None] = '093a3b670ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('covers', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seckill',
    sa.Column('sk_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='秒杀价'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='秒杀开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='秒杀结束时间'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('max_sk_count', sa.Integer(), nullable=True, comment='秒杀数量'),
    sa.Column('sk_per_max_count', sa.Integer(), nullable=True, comment='每人最多秒杀数量'),
    sa.Column('commodity_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('UNPAYED', 'PAYED', 'TRANSIT', 'FINISHED', 'REFUNDING', 'REFUNDED', name='orderstatusenum'), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('address_id', sa.String(length=200), nullable=True),
    sa.Column('seckill_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['seckill_id'], ['seckill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('seckill')
    op.drop_table('commodity')
    # ### end Alembic commands ###
