"""add stock field

Revision ID: d1df98cc3ec1
Revises: 7901cc21fe9c
Create Date: 2024-08-17 20:51:51.027282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1df98cc3ec1'
down_revision: Union[str, None] = '7901cc21fe9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seckill', sa.Column('stock', sa.Integer(), nullable=True, comment='库存量'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seckill', 'stock')
    # ### end Alembic commands ###
